// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_shopping_cart.Data;

#nullable disable

namespace test_shopping_cart.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240521152300_InitDataBase")]
    partial class InitDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("test_shopping_cart.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("CostPrice")
                        .HasColumnType("double");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SkuName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("3c9af691-60eb-4f38-b2c5-d627fc1eaba0"),
                            CostPrice = 4.5,
                            SkuCode = "S-00001",
                            SkuName = "ดินสอ"
                        },
                        new
                        {
                            ProductId = new Guid("ebd02b56-51bf-4b5b-9021-5365b15bd137"),
                            CostPrice = 7.0,
                            SkuCode = "S-00002",
                            SkuName = "ปากกา"
                        },
                        new
                        {
                            ProductId = new Guid("a40a3223-40b1-47eb-a762-fca7a0ec7566"),
                            CostPrice = 3.0,
                            SkuCode = "S-00003",
                            SkuName = "ยางลบ"
                        },
                        new
                        {
                            ProductId = new Guid("f4c3fd26-f750-43f5-86b0-25f38408a9a3"),
                            CostPrice = 6.0,
                            SkuCode = "S-00004",
                            SkuName = "ไม้บรรทัด"
                        },
                        new
                        {
                            ProductId = new Guid("62351332-8db4-4930-b219-a6af900efb7e"),
                            CostPrice = 12.5,
                            SkuCode = "S-00005",
                            SkuName = "น้ํายาลบคําผิด"
                        },
                        new
                        {
                            ProductId = new Guid("7aacf121-55cd-45ea-afa7-b368b42dbddc"),
                            CostPrice = 70.0,
                            SkuCode = "S-00006",
                            SkuName = "กระดาษ a4 80 แกรม(500แผ่น)"
                        },
                        new
                        {
                            ProductId = new Guid("48cd0b38-108f-405f-835a-d0deba24a2c6"),
                            CostPrice = 40.0,
                            SkuCode = "S-00007",
                            SkuName = "แม็กเย็บกระดาษ เบอร์ 35"
                        });
                });

            modelBuilder.Entity("test_shopping_cart.Models.StockInven", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAction")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("StockInven");
                });

            modelBuilder.Entity("test_shopping_cart.Models.StockInven", b =>
                {
                    b.HasOne("test_shopping_cart.Models.Product", "Product")
                        .WithOne("StockInven")
                        .HasForeignKey("test_shopping_cart.Models.StockInven", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("test_shopping_cart.Models.Product", b =>
                {
                    b.Navigation("StockInven");
                });
#pragma warning restore 612, 618
        }
    }
}
